<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406185854" tests="1" time="0.686">
	<testcase classname="InequalityTest" name="test_IsClassify_1" time="0.686">
		<error message="[{'pct': 90, 'id': 500, 'type': 1}] != 500" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 25, in test_IsClassify_1
    self.assertEqual(Actuval, expected)
AssertionError: [{'pct': 90, 'id': 500, 'type': 1}] != 500
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[1024
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
