<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406174021" tests="1" time="0.676">
	<testcase classname="InequalityTest" name="test_IsClassify_1" time="0.676">
		<error message="&quot;{'categories': [{'type': 1, 'pct': 90, '[299 chars]e '}&quot; != 500" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 25, in test_IsClassify_1
    self.assertEqual(Actuval, expected)
AssertionError: "{'categories': [{'type': 1, 'pct': 90, '[299 chars]e '}" != 500
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[200
{'categories': [{'type': 1, 'pct': 90, 'id': 500}], 'entities': [{'text': '3', 'startPos': 189, 'id': 5}], 'bodyS2': 'damn girl   you looked good in that skirt today   i think you should consider wearing that every day  everyone will want to buy from your department   i bet if you wear that skirt at least 3 times a week  sales will triple '}
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
