<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406153309" tests="1" time="0.675">
	<testcase classname="InequalityTest" name="test_IsEmail_1" time="0.675">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 31, in test_IsEmail_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 20, in Ontobi_API
    j = r.json()
  File "C:\Users\CHRIS\PycharmProjects\Requests\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[404
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
